baseURL = 'https://alexeinstein.github.io/'
languageCode = 'en-us'
title = 'AlexEinstein Blog'
author = 'Alex'
theme = 'hugo-PaperMod-master'
[params.busuanzi]
  enable = true
  # 是否开启全站独立访客数
  site_uv = true
  # 全站独立访客数前的图标或提示语
  site_uv_pre = '<i class="fa fa-user"></i>' 
  # 全站独立访客数后的图标或提示语
  site_uv_post = ''
  # 是否开启全站浏览量
  site_pv = true
  # 全站浏览量前的图标或提示语
  site_pv_pre = '<i class="fa fa-eye"></i>'
  # 全站浏览量后的图标或提示语
  site_pv_post = ''
  # 是否开启单页浏览量
  page_pv = true
  # 单页浏览量前的图标或提示语
  page_pv_pre = '<i class="far fa-eye fa-fw"></i>'
  # 单页浏览量后的图标或提示语
  page_pv_post = ''

[params.profileMode]
  enabled = true
  title = "AlexEinstein blog"
  subtitle = ""
  imageUrl = "/einstein.ico"
  imageTitle = ""
  imageWidth = 120
  imageHeight = 120

  [[params.profileMode.buttons]]
   name = "序言"
   url = "/start"
   name = "文章"
   url = "/posts"
   name = "友链"
   url = "/friend"

[[params.socialIcons]]
 name = "github"
 url = "https://github.com/AlexEinstein"

[[params.socialIcons]]
 name = "WeChat"
 url = ""
[[params.socialIcons]]
 name = "QQ"
 url = ""
[[params.socialIcons]]
 name = "email"
 url = "mailto:AlexEinstein080103@outlook.com"
